#:schema node_modules/wrangler/config-schema.json
name = "r2-dir-list-frontend"
account_id = "2dc3483aa62d4b5dc774ec04713893de"
main = ".worker-next/index.mjs"

compatibility_date = "2024-09-26"
compatibility_flags = ["nodejs_compat"]

# Minification helps to keep the Worker bundle size down and improve start up time.
minify = true

# Use the new Workers + Assets to host the static frontend files
assets = { directory = ".worker-next/assets", binding = "ASSETS" }

r2_buckets  = [
    { binding = "BUCKET_POI_DB", bucket_name = "poi-db"},
    { binding = "BUCKET_POI_NIGHTLIES", bucket_name = "poi-nightlies"},
]

[[kv_namespaces]]
binding = "NEXT_CACHE_WORKERS_KV"
id = "a73835e296554c0e8a4c83a6f5dc3493"
